default: ppe

environments:
    ppe:
        baseURI: "http://ppebaseurl"
        basePath: "/v1"
        auth:
            type: bearer
            token: "ppe-token-here"
        headers:
            Content-Type: "application/json"
            Accept: "application/json"
        timeout:
            connection: 5000
            socket: 5000
        logging: true
    CI1:
        baseURI: "http://ci-baseurl"
        basePath: "/v1"
        auth:
            type: bearer
            token: "dev-token-here"
        headers:
            Content-Type: "application/json"
            Accept: "application/json"
        timeout:
            connection: 5000
            socket: 5000
        logging: true

proxy:
    enabled: false
    host: "proxy.example.com"
    port: 8080
